DROP DATABASE IF EXISTS ResearchLabManager;
CREATE DATABASE ResearchLabManager;
USE ResearchLabManager;

-- 1. Base Table: LAB_MEMBER
CREATE TABLE LAB_MEMBER (
    MID INT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    JOINDATE DATE,
    MTYPE VARCHAR(20), 
    MENTOR INT,
    FOREIGN KEY (MENTOR) REFERENCES LAB_MEMBER(MID)
);

-- 2. Subtype: FACULTY
CREATE TABLE FACULTY (
    MID INT PRIMARY KEY,
    DEPARTMENT VARCHAR(100),
    FOREIGN KEY (MID) REFERENCES LAB_MEMBER(MID) ON DELETE CASCADE
);

-- 3. Subtype: STUDENT
CREATE TABLE STUDENT (
    MID INT PRIMARY KEY,
    SID VARCHAR(20) UNIQUE,
    LEVEL VARCHAR(20),
    MAJOR VARCHAR(50),
    FOREIGN KEY (MID) REFERENCES LAB_MEMBER(MID) ON DELETE CASCADE
);

-- 4. Subtype: COLLABORATOR
CREATE TABLE COLLABORATOR (
    MID INT PRIMARY KEY,
    AFFILIATION VARCHAR(100),
    BIOGRAPHY TEXT,
    FOREIGN KEY (MID) REFERENCES LAB_MEMBER(MID) ON DELETE CASCADE
);

-- 5. GRANT (Using backticks because GRANT is a reserved word)
CREATE TABLE `GRANT` (
    GID INT PRIMARY KEY,
    SOURCE VARCHAR(100),
    BUDGET DECIMAL(15, 2),
    STARTDATE DATE,
    DURATION INT
);

-- 6. PROJECT
CREATE TABLE PROJECT (
    PID INT PRIMARY KEY,
    TITLE VARCHAR(200),
    SDATE DATE,
    EDATE DATE,
    EDURATION INT,
    LEADER INT NOT NULL,
    FOREIGN KEY (LEADER) REFERENCES FACULTY(MID)
);

-- 7. FUNDS
CREATE TABLE FUNDS (
    GID INT,
    PID INT,
    PRIMARY KEY (GID, PID),
    FOREIGN KEY (GID) REFERENCES `GRANT`(GID),
    FOREIGN KEY (PID) REFERENCES PROJECT(PID)
);

-- 8. WORKS
CREATE TABLE WORKS (
    PID INT,
    MID INT,
    ROLE VARCHAR(50),
    HOURS DECIMAL(5, 2),
    PRIMARY KEY (PID, MID),
    FOREIGN KEY (PID) REFERENCES PROJECT(PID),
    FOREIGN KEY (MID) REFERENCES LAB_MEMBER(MID)
);

-- 9. EQUIPMENT
CREATE TABLE EQUIPMENT (
    EID INT PRIMARY KEY,
    ETYPE VARCHAR(50),
    ENAME VARCHAR(100),
    STATUS VARCHAR(50), -- 'Available', 'In Use'
    PDATE DATE
);

-- 10. USES
CREATE TABLE USES (
    MID INT,
    EID INT,
    SDATE DATE,
    EDATE DATE,
    PURPOSE VARCHAR(255),
    PRIMARY KEY (MID, EID, SDATE),
    FOREIGN KEY (MID) REFERENCES LAB_MEMBER(MID),
    FOREIGN KEY (EID) REFERENCES EQUIPMENT(EID)
);

-- 11. PUBLICATION
CREATE TABLE PUBLICATION (
    PID INT PRIMARY KEY,
    TITLE VARCHAR(255),
    VENUE VARCHAR(100),
    DATE DATE,
    DOI VARCHAR(100)
);

-- 12. PUBLISHES
CREATE TABLE PUBLISHES (
    MID INT,
    PID INT,
    SDATE DATE,
    EDATE DATE,
    PURPOSE VARCHAR(100),
    PRIMARY KEY (MID, PID),
    FOREIGN KEY (MID) REFERENCES LAB_MEMBER(MID),
    FOREIGN KEY (PID) REFERENCES PUBLICATION(PID)
);